---
Mode: UDP
UseSecure: false
# TrustStorePath: 
# TrustStorePassword: 
Host: 127.0.0.1
Port: 514
EPS: 1
SenderCount: 1
LOG_FILE_PATH: Sample.log
SendBufferSize: 65535
LOG_FILE_ENCODING_CODEPAGE: 65001
SEND_ENCODING_CODEPAGE: 65001
